################################################################################################################
###内置应用容器（Tomcat、Jetty、Undertow）配置：
################################################################################################################
server:
  undertow:
    threads:
      io: 8
      worker: 64
  jetty:
    threads:
      acceptors: 8
      selectors: 64

################################################################################################################
###Spring Boot 相关组件（SpringMVC、Freemarker、Session、Cache、DataSource）配置：
################################################################################################################
spring:
  # 数据源配置：
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.54.2.213:3306/jeebiz_admin?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: jeebiz_admin
    password: 5RcLHz6E3AS5LFDh
    # HiKariCP的数据源配置：
    hikari:
      enabled: true
      # 一个连接的最大的生命时间（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上，参考MySQL wait_timeout参数（show variables like '%timeout%';）
      max-lifetime: 1800000
      # 连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
      max-pool-size: 15
      # 最小闲置线程
      min-idle: 5
  # Redis相关配置
  redis:
    # Redis服务器地址
    host: 106.54.2.213
    # Redis服务器连接端口
    port: 6379
    # Database 索引；和其他服务区别开
    #database: 1
    # Redis服务器连接密码（默认为空）
    password: HycBsP5cSp3enyGw

################################################################################################################
###logging (log4j2) 基本配置：
###http://www.cnblogs.com/yhtboke/p/Mybatis.html
################################################################################################################
logging:
  config: classpath:conf/log4j2.xml