DELETE t_data_perms_table;
DELETE t_data_perms_table_columns;
DELETE t_DATA_PERMS_GROUP;
DELETE t_DATA_PERMS;
DELETE t_DATA_PERMS_ITEM;
DELETE t_DATA_PERMS_ROLE_REL;
DELETE t_DATA_PERMS_USER_REL;
DELETE t_DATA_PERMS_GROUP_REL;
DELETE t_DATA_PERMS_GROUP_ROLE_REL;
DELETE t_DATA_PERMS_GROUP_USER_REL;
DELETE t_DATA_PERMS_SPCL;
DELETE t_DATA_PERMS_SPCL_COLUMNS;
DELETE t_DATA_PERMS_SPCL_ROLE_REL;
DELETE t_DATA_PERMS_SPCL_USER_REL;
  