---
apiVersion: v1
kind: Service
metadata:
  name: jeebiz-cloud-sample-webflux-svc
  labels:
    app: jeebiz-cloud-sample-webflux
    micrometer-prometheus-discovery: 'true'
  annotations:
    kubesphere.io/alias-name: Jeebiz Cloud - WebFlux微服务项目示例
    kubesphere.io/description: Jeebiz Cloud - WebFlux微服务项目示例
    prometheus.io/path: /actuator/prometheus
    prometheus.io/port: '50000'
    prometheus.io/scrape: 'true'
spec:
  ports:
    - name: tcp-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: tcp-50000
      protocol: TCP
      port: 50000
      targetPort: 50000     
  selector:
    app: jeebiz-cloud-sample-webflux
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jeebiz-cloud-sample-webflux-deploy
  annotations:
    kubesphere.io/alias-name: Jeebiz Cloud - WebFlux微服务项目示例
    kubesphere.io/description: Jeebiz Cloud - WebFlux微服务项目示例
  labels:
    app: jeebiz-cloud-sample-webflux
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jeebiz-cloud-sample-webflux
  template:
    metadata:
      labels:
        app: jeebiz-cloud-sample-webflux
    spec:
      containers:
        - name: jeebiz-cloud-sample-webflux
          image: >-
            wans-hz-docker.pkg.coding.net/wisdom-edu/docker/jeebiz-cloud-sample-webflux:latest
          ports:
            - name: http-8080
              containerPort: 8080
              protocol: TCP
            - name: management-port
              containerPort: 50000
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: SPRING_CLOUD_NACOS_SERVER-ADDR
              valueFrom:
                configMapKeyRef:
                  name: nacos-config
                  key: spring.cloud.nacos.server-addr
            - name: SPRING_CLOUD_NACOS_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: spring.cloud.nacos.username
                  name: nacos-config
            - name: SPRING_CLOUD_NACOS_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: spring.cloud.nacos.password 
                  name: nacos-config                   
            - name: SPRING_CLOUD_NACOS_CONFIG_NAMESPACE
              valueFrom:
                configMapKeyRef:
                  name: nacos-config
                  key: spring.cloud.nacos.namespace
            - name: SPRING_CLOUD_NACOS_DISCOVERY_NAMESPACE
              valueFrom:
                configMapKeyRef:
                  name: nacos-config
                  key: spring.cloud.nacos.namespace
            - name: JAVA_TOOL_OPTIONS
              value: >-
                -Xms1344M -Xmx1344M -XX:+PrintGCDetails -XX:+PrintGCTimeStamps
                -XX:MetaspaceSize=200M -XX:MaxMetaspaceSize=200M
                -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:NewRatio=1
                -XX:SurvivorRatio=4 -XX:GCLogFileSize=20m
                -XX:+HeapDumpOnOutOfMemoryError
                -XX:HeapDumpPath=/logs/heaperror.log
                -Xloggc:/logs/gcerror.log         
          resources: {}
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 50000
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 50000
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 9
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 50000
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          lifecycle:
            preStop:
              exec:
                command:
                  - curl
                  - '-XPOST'
                  - '127.0.0.1:50000/actuator/shutdown'
          imagePullPolicy: Always
      imagePullSecrets:
        - name: coding-registry-cred-sample
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: jeebiz-cloud-sample-webflux
                topologyKey: kubernetes.io/hostname        